apply plugin: 'com.android.application'

android {
    namespace 'com.minik.launcher'
    compileSdk 36

    defaultConfig {
        applicationId "com.minik.launcher"
        minSdk 24
        targetSdk 36
        versionCode 4
        versionName "2.1.1"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // No external dependencies for minimal size
}
